// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "go-zero-demo/mall/order/api/internal/handler/order"
	"go-zero-demo/mall/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/order/get/:id",
					Handler: order.GetOrderHandler(serverCtx),
				},
			}...,
		),
	)
}
