// Code generated by goctl. DO NOT EDIT!
// Source: dic.proto

package server

import (
	"context"

	dic "go-zero-demo/mall/sys/rpc/dic"
	"go-zero-demo/mall/sys/rpc/internal/logic"
	"go-zero-demo/mall/sys/rpc/internal/svc"
)

type DicServer struct {
	svcCtx *svc.ServiceContext
	dic.UnimplementedDicServer
}

func NewDicServer(svcCtx *svc.ServiceContext) *DicServer {
	return &DicServer{
		svcCtx: svcCtx,
	}
}

func (s *DicServer) GetDicById(ctx context.Context, in *dic.IdRequest) (*dic.DicResponse, error) {
	l := logic.NewGetDicByIdLogic(ctx, s.svcCtx)
	return l.GetDicById(in)
}
